# -*- coding: utf-8 -*-
"""Scrap_using_select.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-APoULrGml81a6C1MAiOMGS2DwK38wGf
"""

import requests # pip install requests
from bs4 import BeautifulSoup as bs

r = requests.get("https://keithgalli.github.io/web-scraping/webpage.html")

soup = bs(r.content)

print(soup.prettify())

links=soup.select("a")[2:6]

records=[]
for link in links:
  records.append(link.text)

records

import pandas as pd

df=pd.DataFrame(records, columns=['link'], index=['instagram : ','twitter : ','linkedIn :','tiktok : '])

records

df.to_csv("Links_with_select")

pf=df.to_csv("new", index=['instagram',])

pf

pf

pf

li = soup.select("ul.socials a")

li[0].text

rec=[ link.text for link in li]

"""**Social Media Link**"""

rec

ul=soup.select("li.social a")

r=[u.text  for u in ul]

r

table=soup.prettify()

table

table=soup.select('table.hockey-stats')

table[0]

tab=[tabl for tabl in table]

tab[0]

import pandas as pd

table = soup.select("table.hockey-stats")[0]
columns = table.find("thead").find_all("th")
column_names = [c.string for c in columns]

table_rows = table.find("tbody").find_all("tr")
l = []
for tr in table_rows:
    td = tr.find_all('td')
    row = [str(tr.get_text()).strip() for tr in td]
    l.append(row)

df = pd.DataFrame(l, columns=column_names)
df.head()

